### ISSUE TITLE
Internal Server Error "Class 'DB' not found"

### ISSUE THREAD

**Issue by freakexeuLow** [diller110/AC-Advert#1]
Thanks for the great plugin but I have a problem :3

Error: [https://pastebin.com/7qrUQhSi](https://pastebin.com/7qrUQhSi)

> [globals]
DEBUG=0
UI=view/http/
AUTOLOAD=app/

;'ru' or 'en'. Create file /view/lang/{lang}.php to add new languages
lang="en"
;Dark mode not implemented, change to 1, and edit /view/http/css/styles.dark.less
;Use get argument '?cs' to compile .less to .css (ex. http://yousite.ru/advert?cs)
dark_mode=1
pass="*********"

;DB credentials
db_host="localhost"
db_name="sql37"
db_user="sql37"
db_pass="********"

The password replaced with stars, so what is the problem?

**Comment by diller110** [comment]
Замени <? на <?php в первой строке файла DB.php

**Comment by freakexeuLow** [comment]
Спасибо, это работает.
