### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by VortDyn** [diller110/AC-Advert#2]
Хотел бы узнать из-за чего такое может быть.. Возможно из-за того что у меня строит не InnoDB, а MariaDB
Когда ввожу данные сервер, кидает на advert/ex/server ; которая пустая

![](https://user-images.githubusercontent.com/54004093/64944818-0529e500-d891-11e9-997f-ce162a35fb14.png)

**Comment by Hinja122** [comment]
![image](https://user-images.githubusercontent.com/54004093/64944818-0529e500-d891-11e9-997f-ce162a35fb14.png)
